name: RiskManegementResearch
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - ipython
  - ipykernel
  - pip
  - pip:
    - matplotlib==3.9.1
    - numpy==1.26.4
    - torch==2.2.2
    - yfinance==0.2.41